package com.bjpowernode.p2p.mapper.loan;

import com.bjpowernode.p2p.model.loan.BidInfo;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface BidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Thu Sep 12 12:56:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Thu Sep 12 12:56:01 CST 2019
     */
    int insert(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Thu Sep 12 12:56:01 CST 2019
     */
    int insertSelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Thu Sep 12 12:56:01 CST 2019
     */
    BidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Thu Sep 12 12:56:01 CST 2019
     */
    int updateByPrimaryKeySelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Thu Sep 12 12:56:01 CST 2019
     */
    int updateByPrimaryKey(BidInfo record);

    Double selectTotalBidMoney();

    /**
     * 根据chanpId ，与用户表联查 出最近10条投资记录
     * @return
     */
    List<BidInfo> selectRecentBidInfoListByLoanId(Map<String, Object> map);

    /**
     * 根据用户id查询分页查询投资信息
     * @param map
     * @return
     */
    List<BidInfo> selectRecentBidInfoListByUid(Map map);

    /**
     * 根据用户id查询投资总条数
     * @param map
     * @return
     */

    Long selectTotalBidInfoByUid(HashMap<String, Object> map);

    /**
     * 根据产品id查出投资记录
     * @param id
     * @return
     */
    List<BidInfo> selectBidInfoListByLoanId(Integer id);
}