package com.bjpowernode.p2p.mapper.user;

import com.bjpowernode.p2p.model.user.User;

import java.util.HashMap;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Thu Sep 12 12:56:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Thu Sep 12 12:56:01 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Thu Sep 12 12:56:01 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Thu Sep 12 12:56:01 CST 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Thu Sep 12 12:56:01 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Thu Sep 12 12:56:01 CST 2019
     */
    int updateByPrimaryKey(User record);

    /**
     * 查询平台用户总数
     * @return
     */

    Long selectAllUserCount();

    /**
     * 根据电话查用户信息
     * @param phone
     * @return
     */

    User selectUserInfoByPhone(String phone);

    User SelectUserInfoByPhoneAndLoginPassWord(HashMap map);
}